"""
## Dynamic harvest and transform DAG

Iterates through config files to dynamically build harvest and transform tasks
"""

from datetime import datetime, timedelta
import sys
import os

from airflow import DAG

from airflow.operators.bash import BashOperator
from airflow.operators.python import PythonOperator
from airflow.decorators import dag, task
from airflow.models import Variable
from airflow.models.baseoperator import chain

PATH = os.path.abspath(os.path.dirname(__file__))
SSDN_ENV = Variable.get('ssdn_env')

# Import local module
sys.path.insert(0, PATH)
import ssdn_assets


with DAG('ssdn_dynamic_harvest',
         default_args={'depends_on_past': False,
                       'email': ['airflow.example.org'],
                       'email_on_failure': False,
                       'email_on_retry': False,
                       'retries': 1,
                       'retry_delay': timedelta(minutes=5),
                       'env': {'MANATUS_CONFIG': SSDN_ENV}
                       },
         description='Dynamic harvest test',
         tags=['ssdn', 'harvest', 'transform', 'dynamic', ],
         start_date=datetime(2022, 1, 1),
         schedule_interval='@quarterly',
         catchup=False,
         doc_md=__doc__,
         ) as dag:

    repo_update = BashOperator(
        task_id='repo_update',
        bash_command=f'bash {PATH}/ssdn_assets/repo_update.sh {Variable.get("ssdn_git_repos")}',
    )

    # add_flmem = PythonOperator(
    #     task_id='add_flmem',
    #     python_callable=ssdn_assets.add_json(Variable.get("flmem_data"), ssdn_assets.JSONL_PATH),
    # )

    @task(task_id='add_flmem')
    def add_flmem():
        ssdn_assets.add_json(Variable.get("flmem_data"), ssdn_assets.JSONL_PATH)

    add_data = add_flmem()

    count_records = BashOperator(
        task_id='count_records',
        bash_command=f'python3 {PATH}/ssdn_assets/count_records.py {ssdn_assets.JSONL_PATH}'
    )

    clean_up = BashOperator(
        task_id='clean_up',
        bash_command=f'rm -rf {ssdn_assets.OAI_PATH}/*/*.xml',
    )

    for partner in ssdn_assets.list_config_keys(ssdn_assets.harvest_parser):
        partner_harvest = BashOperator(
            task_id=f'harvest_{partner}',
            bash_command=f'python3 -m manatus --profile ssdn harvest -s {partner}',
            doc_md="""\
            ### Transformation tasks

            Dynamically generated by iterating through configs
            """,
        )

        partner_transform = BashOperator(
            task_id=f'transform_{partner}',
            bash_command=f'python3 -m manatus --profile ssdn transform -s {partner}',
            doc_md="""\
            ### Transformation tasks
            
            Dynamically generated by iterating through configs
            """,
        )

        chain([repo_update, clean_up], partner_harvest, partner_transform, add_data, [count_records])
